f1 = open('Quehuong.txt','r',encoding='utf-8')
nd_l1 = f1.readline()
print("Nội dung dòng 1:",nd_l1)
nd_l2 = f1.readline()
print("Nội dung dòng 2:",nd_l2)
nd_l3 = f1.readline()
print("Nội dung dòng 3:",nd_l3)